name: starfish
channels:
- defaults
- bioconda
- conda-forge
dependencies:
- python>=3.6
- click
- flake8
- jsonschema
- matplotlib
- mypy
- numpy!=1.13.0
- pandas>=0.23.4
- pytest>=3.6.3
- requests
- scikit-image>=0.14.0
- scikit-learn
- scipy
- seaborn
- semantic_version
- showit>=1.1.4
- slicedimage==0.0.4
- sympy
- tqdm
- trackpy
- validators
- xarray
- pip:
  - jsonpath-rw
